repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: check-builtin-literals
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-toml
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
        exclude: 'tests/test_files|assets|moldf/covalent_bonds'
      - id: forbid-new-submodules
      - id: trailing-whitespace
        exclude: 'tests/test_files|assets|moldf/covalent_bonds'

  - repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
      - id: black
        language_version: python3.10

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        additional_dependencies:
          [
            "flake8-bugbear==23.3.23",
            "flake8-logging-format==0.9.0",
            "flake8-implicit-str-concat==0.4.0",
          ]
        exclude: 'tests/test_files|assets'

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: \.py$

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.5.1
    hooks:
      - id: mypy
        exclude: tests/data
        args: ["--pretty", "--show-error-codes"]
        additional_dependencies:
          [
            "keyring==23.13.1",
            "nox==2023.4.22",
            "pytest==7.3.1",
            "types-docutils==0.19.1.9",
            "types-setuptools==67.7.0.1",
            "types-six==1.16.21.8",
          ]

  - repo: https://github.com/mgedmin/check-manifest
    rev: "0.49"
    hooks:
      - id: check-manifest
        stages: [manual]
